services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_lab
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
